development:
  adapter: postgresql
  encoding: utf8
  database: static_development
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: utf8
  database: static_test
  host: localhost
  min_messages: WARNING
